export type Language = 'en' | 'es' | 'fr';

export const LANGUAGES: Record<Language, { name: string; nativeName: string }> = {
  en: { name: 'English', nativeName: 'English' },
  es: { name: 'Spanish', nativeName: 'Español' },
  fr: { name: 'French', nativeName: 'Français' },
};

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.calendar': 'Calendar',
    'nav.tasks': 'Tasks',
    'nav.pet': 'Pet',
    'nav.skillTree': 'Skill Tree',
    'nav.leaderboards': 'Leaderboards',
    'nav.store': 'Store',
    'nav.games': 'Games',
    'nav.settings': 'Settings',
    'nav.insights': 'Insights',

    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.yourTasks': 'Your Tasks',
    'dashboard.completeTask': 'Complete Task',
    'dashboard.noTasks': 'No tasks yet. Create one to get started!',
    'dashboard.level': 'Level',
    'dashboard.experience': 'Experience',
    'dashboard.gems': 'Gems',
    'dashboard.streak': 'Streak',
    'dashboard.days': 'days',
    'dashboard.totalXP': 'Total XP',
    'dashboard.nextLevel': 'Next Level',

    // Calendar
    'calendar.monthView': 'Month View',
    'calendar.weekView': 'Week View',
    'calendar.dayView': 'Day View',
    'calendar.today': 'Today',
    'calendar.previous': 'Previous',
    'calendar.next': 'Next',
    'calendar.monday': 'Monday',
    'calendar.tuesday': 'Tuesday',
    'calendar.wednesday': 'Wednesday',
    'calendar.thursday': 'Thursday',
    'calendar.friday': 'Friday',
    'calendar.saturday': 'Saturday',
    'calendar.sunday': 'Sunday',

    // Tasks
    'tasks.title': 'Tasks',
    'tasks.create': 'Create Task',
    'tasks.edit': 'Edit Task',
    'tasks.delete': 'Delete Task',
    'tasks.complete': 'Complete',
    'tasks.noTasks': 'No tasks. Start creating!',
    'tasks.titleField': 'Title',
    'tasks.description': 'Description',
    'tasks.dueDate': 'Due Date',
    'tasks.priority': 'Priority',
    'tasks.high': 'High',
    'tasks.medium': 'Medium',
    'tasks.low': 'Low',

    // Pet
    'pet.feedWithGems': 'Feed with Gems',
    'pet.feedWithXp': 'Feed with XP',
    'pet.experience': 'Experience',
    'pet.hunger': 'Hunger',
    'pet.happiness': 'Happiness',
    'pet.health': 'Health',
    'pet.customize': 'Customize Your Pet',
    'pet.level': 'Level',
    'pet.stage': 'Stage',
    'pet.name': 'Name',
    'pet.color': 'Color',
    'pet.skin': 'Skin',
    'pet.lastFed': 'Last Fed',
    'pet.selectColor': 'Select Color',
    'pet.selectSkin': 'Select Skin',

    // Settings
    'settings.title': 'Settings',
    'settings.customize': 'Customize your experience',
    'settings.language': 'Language',
    'settings.chooseLanguage': 'Choose Language',
    'settings.theme': 'Theme',
    'settings.appearance': 'Appearance',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.sunset': 'Sunset',
    'settings.ocean': 'Ocean',
    'settings.notifications': 'Notifications',
    'settings.enableNotifications': 'Enable notifications',
    'settings.account': 'Account',
    'settings.exportData': 'Export data',
    'settings.exportJSON': 'Export JSON',
    'settings.resetLevel': 'Reset Level',
    'settings.resetXp': 'Reset XP',
    'settings.languageChanged': 'Language changed',
    'settings.logout': 'Logout',
    'settings.deleteAccount': 'Delete Account',
    'settings.support': 'Support',
    'settings.documentation': 'View Documentation',
    'settings.reportBug': 'Report a Bug',
    'settings.requestFeature': 'Request a Feature',
    'settings.contact': 'Contact Developer',

    // Quests
    'quests.title': 'Quests',
    'quests.available': 'Available Quests',
    'quests.progress': 'Progress',
    'quests.reward': 'Reward',
    'quests.complete': 'Complete',
    'quests.claim': 'Claim Reward',
    'quests.completed': 'Completed',
    'quests.locked': 'Locked',
    'quests.nextQuestIn': 'Next quest in',

    // Store
    'store.title': 'Store',
    'store.gems': 'Gems',
    'store.buy': 'Buy',
    'store.owned': 'Owned',
    'store.price': 'Price',
    'store.themes': 'Themes',
    'store.petColors': 'Pet Colors',
    'store.petSkins': 'Pet Skins',
    'store.insufficientFunds': 'Insufficient Gems',
    'store.purchase': 'Purchase',
    'store.purchased': 'Purchased',

    // Leaderboards
    'leaderboards.title': 'Leaderboards',
    'leaderboards.global': 'Global',
    'leaderboards.friends': 'Friends',
    'leaderboards.rank': 'Rank',
    'leaderboards.player': 'Player',
    'leaderboards.xp': 'XP',
    'leaderboards.level': 'Level',
    'leaderboards.noFriends': 'No friends yet',

    // Skill Tree
    'skillTree.title': 'Skill Tree',
    'skillTree.available': 'Available Skills',
    'skillTree.unlocked': 'Unlocked',
    'skillTree.upgrade': 'Upgrade',
    'skillTree.cost': 'Cost',
    'skillTree.points': 'Points',
    'skillTree.maxLevel': 'Max Level',
    'skillTree.pointsAvailable': 'Points Available',

    // Insights
    'insights.title': 'Personal Insights',
    'insights.productivity': 'Productivity',
    'insights.completionRate': 'Completion Rate',
    'insights.averageTime': 'Average Time',
    'insights.thisWeek': 'This Week',
    'insights.thisMonth': 'This Month',
    'insights.allTime': 'All Time',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.view': 'View',
    'common.hide': 'Hide',

    // Games
    'games.title': 'Brain Stimulation Games',
    'games.subtitle': 'Quick mini-games to earn XP and keep your mind sharp!',
    'games.patternMemory': 'Pattern Memory',
    'games.patternMemoryDesc': 'Watch the tile sequence and repeat it! Each level the sequence gets longer.',
    'games.reactionTest': 'Reaction Test',
    'games.reactionTestDesc': 'Click as fast as possible when the screen flashes! Test your reaction speed.',
    'games.playPatternMemory': 'Play Pattern Memory',
    'games.playReactionTest': 'Play Reaction Test',
    'games.difficulty': 'Difficulty',
    'games.chooseDifficulty': 'Choose Difficulty',
    'games.higherDifficulty': 'Higher difficulty = Faster gameplay & More XP',
    'games.duration': 'Duration',
    'games.reward': 'Reward',
    'games.remaining': 'Games Remaining Today',
    'games.status': 'Status',
    'games.readyToPlay': 'Ready to Play',
    'games.dailyLimitReached': 'Daily limit reached! Come back tomorrow.',
    'games.nextGameIn': 'Next game available in',
    'games.recentGames': 'Recent Games',
    'games.score': 'Score',
    'games.xp': 'XP',
    'games.level': 'Level',
    'games.dailyInfo': 'Daily limit: 5 games played • Cooldown: 2 minutes between games',
    'games.grantInfo': 'These games grant small amounts of XP and pet XP on top of your tasks!',
    'games.gameOver': 'Game Over!',
    'games.sequenceReached': 'Sequence reached:',
    'games.yourTurn': 'Your turn!',
    'games.watchingSequence': 'Watching sequence...',
    'games.reactionTime': 'Your reaction time:',
    'games.getReady': 'Get ready...',
    'games.clickNow': 'CLICK NOW!',
    'games.tooEarly': 'Too early! Wait for the signal.',
    'games.avgReactionTime': 'Average reaction time:',
    'games.cancelGame': 'Cancel Game',
    'games.gotIt': 'Got it! Continue',

    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signUp': 'Sign Up',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.createAccount': 'Create Account',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.signIn': 'Sign In',
  },
  es: {
    // Navigation
    'nav.dashboard': 'Panel de Control',
    'nav.calendar': 'Calendario',
    'nav.tasks': 'Tareas',
    'nav.pet': 'Mascota',
    'nav.skillTree': 'Árbol de Habilidades',
    'nav.leaderboards': 'Clasificaciones',
    'nav.store': 'Tienda',
    'nav.games': 'Juegos',
    'nav.settings': 'Configuración',
    'nav.insights': 'Perspectivas',

    // Dashboard
    'dashboard.welcome': 'Bienvenido',
    'dashboard.yourTasks': 'Tus Tareas',
    'dashboard.completeTask': 'Completar Tarea',
    'dashboard.noTasks': '¡Sin tareas aún. Crea una para empezar!',
    'dashboard.level': 'Nivel',
    'dashboard.experience': 'Experiencia',
    'dashboard.gems': 'Gemas',
    'dashboard.streak': 'Racha',
    'dashboard.days': 'días',
    'dashboard.totalXP': 'XP Total',
    'dashboard.nextLevel': 'Próximo Nivel',

    // Calendar
    'calendar.monthView': 'Vista Mensual',
    'calendar.weekView': 'Vista Semanal',
    'calendar.dayView': 'Vista Diaria',
    'calendar.today': 'Hoy',
    'calendar.previous': 'Anterior',
    'calendar.next': 'Siguiente',
    'calendar.monday': 'Lunes',
    'calendar.tuesday': 'Martes',
    'calendar.wednesday': 'Miércoles',
    'calendar.thursday': 'Jueves',
    'calendar.friday': 'Viernes',
    'calendar.saturday': 'Sábado',
    'calendar.sunday': 'Domingo',

    // Tasks
    'tasks.title': 'Tareas',
    'tasks.create': 'Crear Tarea',
    'tasks.edit': 'Editar Tarea',
    'tasks.delete': 'Eliminar Tarea',
    'tasks.complete': 'Completar',
    'tasks.noTasks': 'Sin tareas. ¡Empieza a crear!',
    'tasks.titleField': 'Título',
    'tasks.description': 'Descripción',
    'tasks.dueDate': 'Fecha de Vencimiento',
    'tasks.priority': 'Prioridad',
    'tasks.high': 'Alta',
    'tasks.medium': 'Media',
    'tasks.low': 'Baja',

    // Pet
    'pet.feedWithGems': 'Alimentar con Gemas',
    'pet.feedWithXp': 'Alimentar con XP',
    'pet.experience': 'Experiencia',
    'pet.hunger': 'Hambre',
    'pet.happiness': 'Felicidad',
    'pet.health': 'Salud',
    'pet.customize': 'Personaliza tu Mascota',
    'pet.level': 'Nivel',
    'pet.stage': 'Etapa',
    'pet.name': 'Nombre',
    'pet.color': 'Color',
    'pet.skin': 'Apariencia',
    'pet.lastFed': 'Última Alimentación',
    'pet.selectColor': 'Seleccionar Color',
    'pet.selectSkin': 'Seleccionar Apariencia',

    // Settings
    'settings.title': 'Configuración',
    'settings.customize': 'Personaliza tu experiencia',
    'settings.language': 'Idioma',
    'settings.chooseLanguage': 'Elegir Idioma',
    'settings.theme': 'Tema',
    'settings.appearance': 'Apariencia',
    'settings.light': 'Claro',
    'settings.dark': 'Oscuro',
    'settings.sunset': 'Atardecer',
    'settings.ocean': 'Océano',
    'settings.notifications': 'Notificaciones',
    'settings.enableNotifications': 'Habilitar notificaciones',
    'settings.account': 'Cuenta',
    'settings.exportData': 'Exportar datos',
    'settings.exportJSON': 'Exportar JSON',
    'settings.resetLevel': 'Reiniciar Nivel',
    'settings.resetXp': 'Reiniciar XP',
    'settings.languageChanged': 'Idioma cambiado',
    'settings.logout': 'Cerrar Sesión',
    'settings.deleteAccount': 'Eliminar Cuenta',
    'settings.support': 'Apoyo',
    'settings.documentation': 'Ver Documentación',
    'settings.reportBug': 'Reportar un Error',
    'settings.requestFeature': 'Solicitar una Función',
    'settings.contact': 'Contactar al Desarrollador',

    // Quests
    'quests.title': 'Misiones',
    'quests.available': 'Misiones Disponibles',
    'quests.progress': 'Progreso',
    'quests.reward': 'Recompensa',
    'quests.complete': 'Completar',
    'quests.claim': 'Reclamar Recompensa',
    'quests.completed': 'Completado',
    'quests.locked': 'Bloqueado',
    'quests.nextQuestIn': 'Próxima misión en',

    // Store
    'store.title': 'Tienda',
    'store.gems': 'Gemas',
    'store.buy': 'Comprar',
    'store.owned': 'Poseído',
    'store.price': 'Precio',
    'store.themes': 'Temas',
    'store.petColors': 'Colores de Mascota',
    'store.petSkins': 'Apariencias de Mascota',
    'store.insufficientFunds': 'Gemas Insuficientes',
    'store.purchase': 'Comprar',
    'store.purchased': 'Comprado',

    // Leaderboards
    'leaderboards.title': 'Clasificaciones',
    'leaderboards.global': 'Global',
    'leaderboards.friends': 'Amigos',
    'leaderboards.rank': 'Rango',
    'leaderboards.player': 'Jugador',
    'leaderboards.xp': 'XP',
    'leaderboards.level': 'Nivel',
    'leaderboards.noFriends': 'Sin amigos aún',

    // Skill Tree
    'skillTree.title': 'Árbol de Habilidades',
    'skillTree.available': 'Habilidades Disponibles',
    'skillTree.unlocked': 'Desbloqueado',
    'skillTree.upgrade': 'Mejorar',
    'skillTree.cost': 'Costo',
    'skillTree.points': 'Puntos',
    'skillTree.maxLevel': 'Nivel Máximo',
    'skillTree.pointsAvailable': 'Puntos Disponibles',

    // Insights
    'insights.title': 'Perspectivas Personales',
    'insights.productivity': 'Productividad',
    'insights.completionRate': 'Tasa de Finalización',
    'insights.averageTime': 'Tiempo Promedio',
    'insights.thisWeek': 'Esta Semana',
    'insights.thisMonth': 'Este Mes',
    'insights.allTime': 'Todo el Tiempo',

    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.close': 'Cerrar',
    'common.submit': 'Enviar',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.search': 'Buscar',
    'common.filter': 'Filtro',
    'common.sort': 'Ordenar',
    'common.add': 'Agregar',
    'common.remove': 'Quitar',
    'common.view': 'Ver',
    'common.hide': 'Ocultar',

    // Games
    'games.title': 'Juegos de Estimulación Cerebral',
    'games.subtitle': '¡Mini-juegos rápidos para ganar XP y mantener tu mente aguda!',
    'games.patternMemory': 'Memoria de Patrones',
    'games.patternMemoryDesc': '¡Observa la secuencia de azulejos y repítela! Cada nivel la secuencia se hace más larga.',
    'games.reactionTest': 'Prueba de Reacción',
    'games.reactionTestDesc': '¡Haz clic lo más rápido posible cuando la pantalla destelle! Prueba tu velocidad de reacción.',
    'games.playPatternMemory': 'Jugar Memoria de Patrones',
    'games.playReactionTest': 'Jugar Prueba de Reacción',
    'games.difficulty': 'Dificultad',
    'games.chooseDifficulty': 'Elegir Dificultad',
    'games.higherDifficulty': 'Mayor dificultad = Juego más rápido y más XP',
    'games.duration': 'Duración',
    'games.reward': 'Recompensa',
    'games.remaining': 'Juegos Restantes Hoy',
    'games.status': 'Estado',
    'games.readyToPlay': 'Listo para Jugar',
    'games.dailyLimitReached': '¡Límite diario alcanzado! Vuelve mañana.',
    'games.nextGameIn': 'Próximo juego disponible en',
    'games.recentGames': 'Juegos Recientes',
    'games.score': 'Puntuación',
    'games.xp': 'XP',
    'games.level': 'Nivel',
    'games.dailyInfo': 'Límite diario: 5 juegos jugados • Tiempo de espera: 2 minutos entre juegos',
    'games.grantInfo': '¡Estos juegos otorgan pequeñas cantidades de XP y XP de mascota además de tus tareas!',
    'games.gameOver': '¡Fin del Juego!',
    'games.sequenceReached': 'Secuencia alcanzada:',
    'games.yourTurn': '¡Tu turno!',
    'games.watchingSequence': 'Observando secuencia...',
    'games.reactionTime': 'Tu tiempo de reacción:',
    'games.getReady': 'Prepárate...',
    'games.clickNow': '¡HALE AHORA!',
    'games.tooEarly': '¡Demasiado pronto! Espera la señal.',
    'games.avgReactionTime': 'Tiempo promedio de reacción:',
    'games.cancelGame': 'Cancelar Juego',
    'games.gotIt': '¡Entendido! Continuar',

    // Auth
    'auth.login': 'Iniciar Sesión',
    'auth.logout': 'Cerrar Sesión',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.signUp': 'Registrarse',
    'auth.forgotPassword': '¿Olvidaste tu Contraseña?',
    'auth.createAccount': 'Crear Cuenta',
    'auth.enterEmail': 'Ingresa tu correo',
    'auth.enterPassword': 'Ingresa tu contraseña',
    'auth.signIn': 'Iniciar Sesión',
  },
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de Bord',
    'nav.calendar': 'Calendrier',
    'nav.tasks': 'Tâches',
    'nav.pet': 'Animal de Compagnie',
    'nav.skillTree': 'Arbre de Compétences',
    'nav.leaderboards': 'Classements',
    'nav.store': 'Boutique',
    'nav.games': 'Jeux',
    'nav.settings': 'Paramètres',
    'nav.insights': 'Aperçus',

    // Dashboard
    'dashboard.welcome': 'Bienvenue',
    'dashboard.yourTasks': 'Vos Tâches',
    'dashboard.completeTask': 'Compléter la Tâche',
    'dashboard.noTasks': 'Aucune tâche pour le moment. Créez-en une pour commencer!',
    'dashboard.level': 'Niveau',
    'dashboard.experience': 'Expérience',
    'dashboard.gems': 'Gemmes',
    'dashboard.streak': 'Série',
    'dashboard.days': 'jours',
    'dashboard.totalXP': 'XP Total',
    'dashboard.nextLevel': 'Prochain Niveau',

    // Calendar
    'calendar.monthView': 'Affichage Mensuel',
    'calendar.weekView': 'Affichage Hebdomadaire',
    'calendar.dayView': 'Affichage Journalier',
    'calendar.today': 'Aujourd\'hui',
    'calendar.previous': 'Précédent',
    'calendar.next': 'Suivant',
    'calendar.monday': 'Lundi',
    'calendar.tuesday': 'Mardi',
    'calendar.wednesday': 'Mercredi',
    'calendar.thursday': 'Jeudi',
    'calendar.friday': 'Vendredi',
    'calendar.saturday': 'Samedi',
    'calendar.sunday': 'Dimanche',

    // Tasks
    'tasks.title': 'Tâches',
    'tasks.create': 'Créer une Tâche',
    'tasks.edit': 'Modifier la Tâche',
    'tasks.delete': 'Supprimer la Tâche',
    'tasks.complete': 'Compléter',
    'tasks.noTasks': 'Pas de tâches. Commencez à créer!',
    'tasks.titleField': 'Titre',
    'tasks.description': 'Description',
    'tasks.dueDate': 'Date d\'Échéance',
    'tasks.priority': 'Priorité',
    'tasks.high': 'Élevée',
    'tasks.medium': 'Moyenne',
    'tasks.low': 'Basse',

    // Pet
    'pet.feedWithGems': 'Nourrir avec des Gemmes',
    'pet.feedWithXp': 'Nourrir avec de l\'XP',
    'pet.experience': 'Expérience',
    'pet.hunger': 'Faim',
    'pet.happiness': 'Bonheur',
    'pet.health': 'Santé',
    'pet.customize': 'Personnalisez Votre Animal',
    'pet.level': 'Niveau',
    'pet.stage': 'Étape',
    'pet.name': 'Nom',
    'pet.color': 'Couleur',
    'pet.skin': 'Apparence',
    'pet.lastFed': 'Dernier Repas',
    'pet.selectColor': 'Sélectionner Couleur',
    'pet.selectSkin': 'Sélectionner Apparence',

    // Settings
    'settings.title': 'Paramètres',
    'settings.customize': 'Personnalisez votre expérience',
    'settings.language': 'Langue',
    'settings.chooseLanguage': 'Choisir la Langue',
    'settings.theme': 'Thème',
    'settings.appearance': 'Apparence',
    'settings.light': 'Clair',
    'settings.dark': 'Sombre',
    'settings.sunset': 'Coucher de Soleil',
    'settings.ocean': 'Océan',
    'settings.notifications': 'Notifications',
    'settings.enableNotifications': 'Activer les notifications',
    'settings.account': 'Compte',
    'settings.exportData': 'Exporter les données',
    'settings.exportJSON': 'Exporter JSON',
    'settings.resetLevel': 'Réinitialiser le Niveau',
    'settings.resetXp': 'Réinitialiser XP',
    'settings.languageChanged': 'Langue modifiée',
    'settings.logout': 'Déconnexion',
    'settings.deleteAccount': 'Supprimer le Compte',
    'settings.support': 'Support',
    'settings.documentation': 'Voir la Documentation',
    'settings.reportBug': 'Signaler un Bug',
    'settings.requestFeature': 'Demander une Fonctionnalité',
    'settings.contact': 'Contacter le Développeur',

    // Quests
    'quests.title': 'Quêtes',
    'quests.available': 'Quêtes Disponibles',
    'quests.progress': 'Progrès',
    'quests.reward': 'Récompense',
    'quests.complete': 'Compléter',
    'quests.claim': 'Réclamer la Récompense',
    'quests.completed': 'Complété',
    'quests.locked': 'Verrouillé',
    'quests.nextQuestIn': 'Prochaine quête dans',

    // Store
    'store.title': 'Boutique',
    'store.gems': 'Gemmes',
    'store.buy': 'Acheter',
    'store.owned': 'Possédé',
    'store.price': 'Prix',
    'store.themes': 'Thèmes',
    'store.petColors': 'Couleurs d\'Animal',
    'store.petSkins': 'Apparences d\'Animal',
    'store.insufficientFunds': 'Gemmes Insuffisantes',
    'store.purchase': 'Acheter',
    'store.purchased': 'Acheté',

    // Leaderboards
    'leaderboards.title': 'Classements',
    'leaderboards.global': 'Mondial',
    'leaderboards.friends': 'Amis',
    'leaderboards.rank': 'Rang',
    'leaderboards.player': 'Joueur',
    'leaderboards.xp': 'XP',
    'leaderboards.level': 'Niveau',
    'leaderboards.noFriends': 'Pas d\'amis pour le moment',

    // Skill Tree
    'skillTree.title': 'Arbre de Compétences',
    'skillTree.available': 'Compétences Disponibles',
    'skillTree.unlocked': 'Déverrouillé',
    'skillTree.upgrade': 'Améliorer',
    'skillTree.cost': 'Coût',
    'skillTree.points': 'Points',
    'skillTree.maxLevel': 'Niveau Maximum',
    'skillTree.pointsAvailable': 'Points Disponibles',

    // Insights
    'insights.title': 'Aperçus Personnels',
    'insights.productivity': 'Productivité',
    'insights.completionRate': 'Taux d\'Achèvement',
    'insights.averageTime': 'Temps Moyen',
    'insights.thisWeek': 'Cette Semaine',
    'insights.thisMonth': 'Ce Mois',
    'insights.allTime': 'Tous les Temps',

    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.close': 'Fermer',
    'common.submit': 'Soumettre',
    'common.confirm': 'Confirmer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.add': 'Ajouter',
    'common.remove': 'Supprimer',
    'common.view': 'Afficher',
    'common.hide': 'Masquer',

    // Games
    'games.title': 'Jeux de Stimulation Cérébrale',
    'games.subtitle': 'Mini-jeux rapides pour gagner de l\'XP et garder votre esprit alerte!',
    'games.patternMemory': 'Mémoire de Motifs',
    'games.patternMemoryDesc': 'Regardez la séquence de carreaux et répétez-la! Chaque niveau, la séquence devient plus longue.',
    'games.reactionTest': 'Test de Réaction',
    'games.reactionTestDesc': 'Cliquez dès que possible lorsque l\'écran s\'allume! Testez votre vitesse de réaction.',
    'games.playPatternMemory': 'Jouer à la Mémoire de Motifs',
    'games.playReactionTest': 'Jouer au Test de Réaction',
    'games.difficulty': 'Difficulté',
    'games.chooseDifficulty': 'Choisir la Difficulté',
    'games.higherDifficulty': 'Difficulté plus élevée = Jeu plus rapide et plus de XP',
    'games.duration': 'Durée',
    'games.reward': 'Récompense',
    'games.remaining': 'Jeux Restants Aujourd\'hui',
    'games.status': 'Statut',
    'games.readyToPlay': 'Prêt à Jouer',
    'games.dailyLimitReached': 'Limite quotidienne atteinte! Revenez demain.',
    'games.nextGameIn': 'Prochain jeu disponible dans',
    'games.recentGames': 'Jeux Récents',
    'games.score': 'Score',
    'games.xp': 'XP',
    'games.level': 'Niveau',
    'games.dailyInfo': 'Limite quotidienne: 5 jeux joués • Délai d\'attente: 2 minutes entre les jeux',
    'games.grantInfo': 'Ces jeux accordent de petites quantités de XP et d\'XP pour animal en plus de vos tâches!',
    'games.gameOver': 'Fin du Jeu!',
    'games.sequenceReached': 'Séquence atteinte:',
    'games.yourTurn': 'Votre tour!',
    'games.watchingSequence': 'Observation de la séquence...',
    'games.reactionTime': 'Votre temps de réaction:',
    'games.getReady': 'Préparez-vous...',
    'games.clickNow': 'CLIQUEZ MAINTENANT!',
    'games.tooEarly': 'Trop tôt! Attendez le signal.',
    'games.avgReactionTime': 'Temps de réaction moyen:',
    'games.cancelGame': 'Annuler le Jeu',
    'games.gotIt': 'Compris! Continuer',

    // Auth
    'auth.login': 'Connexion',
    'auth.logout': 'Déconnexion',
    'auth.email': 'E-mail',
    'auth.password': 'Mot de Passe',
    'auth.signUp': 'S\'inscrire',
    'auth.forgotPassword': 'Mot de passe oublié?',
    'auth.createAccount': 'Créer un Compte',
    'auth.enterEmail': 'Entrez votre e-mail',
    'auth.enterPassword': 'Entrez votre mot de passe',
    'auth.signIn': 'Se Connecter',
  },
};

export const getTranslation = (language: Language, key: string): string => {
  return translations[language][key] || translations.en[key] || key;
};
